# toolchain to ensure .bin compilation for riscv systems
# thanks to https://github.com/melastmohican/pinecone-blinky for the fix
[toolchain]
channel = "stable"
components = [ "rust-src", "rustfmt" ]
targets = [ "riscv32imac-unknown-none-elf" ]
